### ISSUE TITLE
Can't compile on Windows 10

### ISSUE THREAD

**Issue by nonodesu** [kambala-decapitator/MedianXLOfflineTools#1]
Hello.
I am unable to compile the project.
Steps I've taken:
1. Install Visual Studio 2019 Community
2. Install Qt 4.8.7 (qt-opensource-windows-x86-vs2010-4.8.7.exe)
3. Install Qt Vs Tools extension
4. Add Qt 4.8.7 in the Qt Versions settings in the extension
5. Open MedianXLOfflineTools.sln (from MedianXLOfflineTools-0.6.4.zip) and try to build it

I get the following error:

> 1>qtmaind.lib(qtmain_win.obj) : error LNK2038: mismatch detected for '_MSC_VER': value '1600' doesn't match value '1900' in allstatsdialog.obj
> 1>E:\dev\cpp\MedianXLOfflineTools-0.6.4\..\Debug\MedianXLOfflineTools.exe : fatal error LNK1319: 1 mismatches detected
> 1>Done building project "MedianXLOfflineTools.vcxproj" -- FAILED.
> ========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

Detailed log:
https://pastebin.com/ERcYRXYt

**Comment by kambala-decapitator** [comment]
You must use Qt version that was built with the same compiler you're using. In your case:

> Visual Studio **2019**
> qt-opensource-windows-x86-**vs2010**-4.8.7

Either compile 4.8.7 from source with VS 2019 or use Qt 5 (it has binary package for 2019).

**Comment by nonodesu** [comment]
Okay, I have made it work in VS2013 and now at least know that it does compile, that will suffice for now.
It seems that making it work in VS2019 will take some more tinkering, but thanks for pointing me in the right direction.
