### ISSUE TITLE
[Question] Item prob decoding

### ISSUE THREAD

**Issue by shinrel22** [kambala-decapitator/MedianXLOfflineTools#3]
Regarding to your [props.tsv file here](https://github.com/kambala-decapitator/MedianXLOfflineTools/blob/main/utils/txt_parser/generated/en/props.tsv)

Probs:
code 48 - to Minimum Fire Damage - 12 bits
code 49 - to Maximum Fire Damage - 12 bits

So the binary code for "Adds 100 - 150 fire damage" should be:

| 48 | 100 | 49 | 150 |
| --- | --- | --- | --- |
| 000011000  | 001001100000  | 100011000  | 011010010000 |

But when I decoded the prob in d2s file. It only had this:

| 48 | 100 | 150 |
| --- | --- | --- |
| 000011000  | 001001100000  | 011010010000 |

So how do u handle this?
Or your data is incorrect for MedianXL current version?

**Comment by kambala-decapitator** [comment]
txt (tsv) mod sources in the repo are from Sigma 1.x

**Comment by kambala-decapitator** [comment]
ah sorry, you linked to the generated file. It's from the current version.

**Comment by kambala-decapitator** [comment]
d2s contains correct data, x-y damage is kinda special, see here https://github.com/kambala-decapitator/MedianXLOfflineTools/blob/main/src/itemparser.cpp#L373
