### ISSUE TITLE
No suitable kits found (QtCreator)

### ISSUE THREAD

**Issue by satandidnowrong** [kambala-decapitator/MedianXLOfflineTools#4]
I cannot figure this out right now. Very frustrated.
I installed qt 4..8.7
I installed qt creator
Do I need to install vs 2010??
Is vs 2022 not compatible and I need vs 2019??
Compiler for 2010??
https://i.imgur.com/MCkUu09.png
https://i.imgur.com/jKJaXxg.png
I don't under stand bro I am very frustrated.
mb if I use this?
https://i.imgur.com/4UTtlPa.png
mb this?
https://i.imgur.com/5rw1M71.png
nope that's not the compiler..
trying to use
https://stackoverflow.com/questions/68668084/installing-a-compiler-for-qt4-8-7-on-windows10
bro wtf you did not go through all of this i don't under stand what i need to do please assist
is this needed?
https://i.imgur.com/AX9x3VF.png
found
https://doc.qt.io/qt-6/windows-deployment.html
it's working now.
thanks any ways. delete if you'd like mb some one else can use this as a somewhat tarnished guide.
i installed qt5 in stead and can at least build and see the project in qt creator
but now when build and run exe it says stuff like qt5 dll missing not found ugh
ok i see the release is bundled with these files i will see how to have build place them in the build

**Comment by satandidnowrong** [comment]
what a huge speedbump (forgot to close earlier)
it's handled
thanks for this project

**Comment by kambala-decapitator** [comment]
Qt 4 is very old, to use it with modern compilers you'll have to build it yourself.

The easiest is to use Qt 5 that has prebuilt binaries for msvc2019.

The project doesn't support Qt 6 yet.

**Comment by satandidnowrong** [comment]
Thanks for response. I have a small pull request coming your way in about 10 minutes.
I eventually used precompiled qt5 and just now build qt5 from source be cause VS2022 didn't like my mingw qt5.
Very cool that you responded, respect.

**Comment by kambala-decapitator** [comment]
> cause VS2022 didn't like my mingw qt5

well, of course it didn't, because these are different compilers :) For mingw you can use Qt Creator.

**Comment by kambala-decapitator** [comment]
note that you can install msvc2019 toolchain (compiler) and use it inside VS 2022

**Comment by satandidnowrong** [comment]
How would msvc2019 help? (sincerely wondering, from ignorance)
My main issue is seeing so many red underlines. I am trying to diagnose this. I am able to build in qt creator, though not yet in vs. I may be able to under stand more precisely if you could list which [distribution set](https://www.qt.io/offline-installers) you would have gone with?

Would you have used [this](https://download.qt.io/official_releases/vsaddin/2.5.2/qt-vsaddin-msvc2019-2.5.2-rev.01.vsix.mirrorlist) or [this](https://download.qt.io/official_releases/vsaddin/1.2.5/qt-vs-addin-1.2.5.exe.mirrorlist)?

Do you use [legacy qt vs tools](https://marketplace.visualstudio.com/items?itemName=TheQtCompany.LEGACYQtVisualStudioTools2019) or do you upgrade the project for use with [current qt vs tools](https://marketplace.visualstudio.com/items?itemName=TheQtCompany.QtVisualStudioTools2022)?

I ended up going with [this](https://download.qt.io/official_releases/qt/5.15/5.15.2/single/qt-everywhere-src-5.15.2.zip.mirrorlist), though with legacy or current qt vs tools, there are red underlines and no build is possible in vs. I would be happy building in qt creator if the red underlines were gone to edit in vs.

**Comment by kambala-decapitator** [comment]
I used online installer to download 5.15.2 binaries for msvc2019, but you can build any 5.15.x from source (better take the latest - 5.15.13).

iirc the project is configured to use the legacy Qt VS tools. I rarely use VS for this project nowadays, mostly just to build it from command line.

**Comment by satandidnowrong** [comment]
Oh to be so skillful.
Any idea about this?
Using legacy tools and compiled source qt.

![CzmSBI4](https://github.com/kambala-decapitator/MedianXLOfflineTools/assets/161235843/b9b49b15-39e3-4680-816c-f77b175e58c4)

This, I just found, is interesting.

![image](https://github.com/kambala-decapitator/MedianXLOfflineTools/assets/161235843/7b9aa092-e925-49fa-8db0-bb4226f1697f)

GOT IT!!! Though, there are a few left. I found some where to start looking, though. Any familiarity with this?

![image](https://github.com/kambala-decapitator/MedianXLOfflineTools/assets/161235843/d9041211-b844-459c-83eb-332500297bf1)

Ahhh check this out

![image](https://github.com/kambala-decapitator/MedianXLOfflineTools/assets/161235843/47171fd1-1445-4b71-b6e3-5024ace537cd)

Those needed widgets and gui modules. What about thissaone?

![image](https://github.com/kambala-decapitator/MedianXLOfflineTools/assets/161235843/b546d5f1-efee-407b-af4e-97a7c0bb7db6)

**Comment by kambala-decapitator** [comment]
right click solution properties - set Qt version. I think you should read the Qt VS tools manual :)

**Comment by satandidnowrong** [comment]
:o surprise pikachu
Qt version is set already ;)
I'll move on then. Hope our codes cross paths again.

Though...

![image](https://github.com/kambala-decapitator/MedianXLOfflineTools/assets/161235843/93afc819-72e6-4d3a-bbb1-e399566e3310)

Well I'm off to figure this one out. See ya coder.
