### ISSUE TITLE
[Question] I can't decompress your DAT files. Any encryptions here?

### ISSUE THREAD

**Issue by shinrel22** [kambala-decapitator/MedianXLOfflineTools#8]
As the title, I can't find any encryption layers it your source code.
Your compress / decompress functions don't do any encryptions.

If they're not supposed not to share, just tell me. It's OK.

**Comment by kambala-decapitator** [comment]
there's no encryption applied, data is simply compressed, see here: https://github.com/kambala-decapitator/MedianXLOfflineTools/blob/main/utils/CompressFiles/main.cpp#L24

you don't even need to look at the dat files as their source is in the repo: https://github.com/kambala-decapitator/MedianXLOfflineTools/tree/main/utils/txt_parser/generated
